import { LightningElement, api, wire } from "lwc";
import { ShowToastEvent } from "lightning/platformShowToastEvent";
import { CloseActionScreenEvent } from "lightning/actions";
import { gql, graphql } from "lightning/uiGraphQLApi";
import { updateRecord } from "lightning/uiRecordApi";

const CONFIG_QUERY = gql`
  query GetFieldLogConfig($configId: ID) {
    uiapi {
      query {
        Field_Log_Config__c(where: { Id: { eq: $configId } }, first: 1) {
          edges {
            node {
              Id
              Source_Object__c {
                value
              }
              Source_Object_Label__c {
                value
              }
              Log_On_Create__c {
                value
              }
              Log_On_Update__c {
                value
              }
              Log_On_Delete__c {
                value
              }
              Log_On_Undelete__c {
                value
              }
              Trigger_Generated__c {
                value
              }
            }
          }
        }
      }
    }
  }
`;

export default class BigotoolGenerateTriggerCode extends LightningElement {
  @api recordId;

  isLoading = true;
  confirmed = false;
  result;
  _config;

  get graphqlVariables() {
    return { configId: this.recordId };
  }

  @wire(graphql, {
    query: CONFIG_QUERY,
    variables: "$graphqlVariables"
  })
  wiredConfig({ data, errors }) {
    this.isLoading = false;
    if (errors && errors.length > 0) {
      this.notifyError("Unable to load trigger status", errors[0]);
      return;
    }
    if (data) {
      const edges = data?.uiapi?.query?.Field_Log_Config__c?.edges;
      if (edges && edges.length > 0) {
        const node = edges[0].node;
        this._config = {
          id: node.Id,
          sourceObject: node.Source_Object__c?.value,
          sourceObjectLabel: node.Source_Object_Label__c?.value,
          logOnCreate: node.Log_On_Create__c?.value,
          logOnUpdate: node.Log_On_Update__c?.value,
          logOnDelete: node.Log_On_Delete__c?.value,
          logOnUndelete: node.Log_On_Undelete__c?.value,
          triggerGenerated: node.Trigger_Generated__c?.value
        };
        // Already generated — skip confirmation and show result directly
        if (this._config.triggerGenerated) {
          this.result = this._buildTriggerCodeResult(true);
        }
      }
    }
  }

  get showConfirm() {
    return !this.isLoading && !this.confirmed && !this.result;
  }

  get showResult() {
    return !!this.result;
  }

  async handleConfirm() {
    this.confirmed = true;
    this.isLoading = true;
    try {
      await updateRecord({
        fields: {
          Id: this._config.id,
          Trigger_Generated__c: true
        }
      });
      this.result = this._buildTriggerCodeResult(false);
      this.dispatchEvent(
        new ShowToastEvent({
          title: "Trigger code generated",
          message: `Trigger ${this.result.triggerName} is ready to add for ${this.result.objectApiName}.`,
          variant: "success"
        })
      );
    } catch (e) {
      this.confirmed = false;
      this.notifyError("Unable to generate trigger code", e);
    } finally {
      this.isLoading = false;
    }
  }

  handleCancel() {
    this.dispatchEvent(new CloseActionScreenEvent());
  }

  handleClose() {
    this.dispatchEvent(new CloseActionScreenEvent());
  }

  async handleCopy() {
    if (!this.result) {
      return;
    }
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(this.result.triggerBody);
        this.dispatchEvent(
          new ShowToastEvent({
            title: "Copied",
            message: "Trigger code copied to clipboard.",
            variant: "success"
          })
        );
      } else {
        this.selectCodeText();
      }
      // eslint-disable-next-line no-unused-vars
    } catch (error) {
      this.selectCodeText();
    }
  }

  selectCodeText() {
    const el = this.template.querySelector(".code-block");
    if (el) {
      const range = document.createRange();
      range.selectNodeContents(el);
      const sel = window.getSelection();
      sel.removeAllRanges();
      sel.addRange(range);
    }
  }

  _buildTriggerCodeResult(alreadyGenerated) {
    const cfg = this._config;
    const objApi = cfg.sourceObject;
    const objLabel = cfg.sourceObjectLabel || objApi;

    const events = [];
    if (cfg.logOnCreate) events.push("after insert");
    if (cfg.logOnUpdate) events.push("after update");
    if (cfg.logOnDelete) events.push("after delete");
    if (cfg.logOnUndelete) events.push("after undelete");
    if (events.length === 0) events.push("after update");
    const eventList = events.join(", ");

    const triggerName = this._buildTriggerName(objApi);

    const triggerBody =
      `// GENERATED by Big Object Tooling — do not edit. Source: Field_Log_Config__c[${objApi}]\n` +
      `trigger ${triggerName} on ${objApi} (${eventList}) {\n` +
      `    BIGOTOOL_ChangeCapture.run('${objApi}', Trigger.operationType, Trigger.oldMap, Trigger.newMap);\n` +
      `}\n`;

    const instructions =
      `How to add this trigger to ${objLabel} (${objApi}):\n` +
      `1. Make sure the reusable handler class BIGOTOOL_ChangeCapture is deployed to this org.\n` +
      `2. In VS Code, create a new Apex Trigger file named ${triggerName}.trigger under force-app/main/default/triggers (or use Setup > Object Manager > ${objLabel} > Triggers > New).\n` +
      `3. Paste the generated code above and save.\n` +
      `4. Deploy the trigger to this org (sf project deploy start) or save it in the Developer Console.\n` +
      `5. Verify the configuration record is Active so logging is enabled at runtime.\n` +
      `Once the trigger is in place, this configuration is marked as Trigger Generated.`;

    return {
      objectApiName: objApi,
      objectLabel: objLabel,
      triggerName,
      triggerBody,
      events: eventList,
      instructions,
      alreadyGenerated
    };
  }

  _buildTriggerName(objApiName) {
    let base = objApiName;
    if (base.toLowerCase().endsWith("__c")) {
      base = base.substring(0, base.length - 3);
    }
    base = base.replace(/[^a-zA-Z0-9_]/g, "");
    if (!base) base = "Object";
    return base + "FieldLogTrigger";
  }

  notifyError(title, error) {
    let message = "Unknown error";
    if (error && error.body && error.body.message) {
      message = error.body.message;
    } else if (error && error.message) {
      message = error.message;
    }
    this.dispatchEvent(new ShowToastEvent({ title, message, variant: "error" }));
  }
}
